# adapted from https://github.com/rdkit/rdkit-tutorials/blob/master/.travis.yml

language: python
python:
  - "3.7"

# switch to new infrastructure
sudo: false

before_install:
  # download and install miniconda
  - wget http://repo.continuum.io/miniconda/Miniconda3-4.1.11-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/conda
  - export PATH="$HOME/conda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # create and activate the build/test environment
  - conda create -q -n tenv python=$TRAVIS_PYTHON_VERSION pip cmake
  - source activate tenv

install:
  - conda install -c openbabel openbabel==2.4.1
  - pip install PyYAML==5.3.1
  - pip install pandas==1.0.3
  - conda install -c rdkit rdkit=2020.03.2.0
  - pip install pytest==5.4.1
  - python setup.py install
  - pip install progress==1.5
  - pip install pytest-cov==2.9.0
  - pip install codecov==2.1.3
  # - pip install Cython --install-option="--no-cython-compile"
  # - pip install ase
  # - pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu100/torch_nightly.html
  # - pip install torchani
  # - pip install goodvibes

before_script:
  - export RDBASE=$CONDA_PREFIX/Library/share/RDKit
  - echo $RDBASE

script:
  - cd tests
  - pytest -v --cov=pyconfort
  - codecov
